### GET all posts
GET http://localhost:8000/posts

### GET one post
GET http://localhost:8000/posts/1

### POST a new post : json
POST http://localhost:8000/posts
Content-Type: application/json

{
    "user_id": 6,
    "title": "Cours de maths",
    "category": "Cours",
    "content": "Bonjour, pour ceux que cela peut intéresser, je peux donner des cours de maths. Me contacter par MP !"
}

### POST : user login (RIGHT LOGIN), json
POST http://localhost:8000/login
Content-Type: application/json

{
    "email": "yligotmi@msn.com",
    "password": "pouet"
}
### POST : user login (RIGHT LOGIN), json
POST http://localhost:8000/login
Content-Type: application/json

{
    "email": "val@gmail.com",
    "password": "tutu"
}

### POST : user login (WRONG LOGIN), json
POST http://localhost:8000/login
Content-Type: application/json

{
    "email": "yligotmi@p.com",
    "password": "pouetp"
}

### POST : register new user : json
POST http://localhost:8000/register
Content-Type: application/json

{
    "firstname": "Eddy",
    "lastname": "Patou",
    "password": "pouet",
    "email": "eddypatou@hotmail.com",
    "birthday": "2001-05-06",
    "hobbies": "BD, arts",
    "study": "Histoire de l'art",
    "bio": "Passionné d'art, je m'intéresse tout particulièrement à la BD",
    "city": "Grenoble"
}

### GET : all likes
GET http://localhost:8000/likes

### GET one like (that doesn't exists)
GET http://localhost:8000/likes
Content-Type: application/json

{
    "user_id": 1,
    "post_id": 1
}

### POST : user likes a post
POST http://localhost:8000/likes
Content-Type: application/json

{
    "user_id": 1,
    "post_id": 1
}

### DELETE : user doesn't like a post anymore
DELETE http://localhost:8000/likes
Content-Type: application/json

{
    "likeId": 14
}

### PUT : manager like / unlike of user
PUT http://localhost:8000/likes
Content-Type: application/json

{
    "user_id": 1,
    "post_id": 1
}
